const API_URL="";
const demo={groups:[{id:"GRP-FORMEN",name:"FORMEN",description:"Formen personel grubu",people:0,docs:0},{id:"GRP-ISCI",name:"İŞÇİ",description:"Saha işçileri",people:0,docs:0},{id:"GRP-MUH",name:"MÜHENDİS",description:"Mühendisler",people:0,docs:0}],links:[],fields:[]};
let selectedField=null;
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const typeNames={text:"Metin",date:"Tarih",phone:"Telefon",email:"E-posta",national_id:"Kimlik No",passport:"Pasaport No",document:"Belge",photo:"Fotoğraf",select:"Açılır Liste",checkbox:"Onay"};

document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
document.querySelectorAll("[data-goto]").forEach(b=>b.onclick=()=>showPage(b.dataset.goto));
$("loginBtn").onclick=()=>{if(!$("username").value.trim()||!$("password").value){$("loginMsg").textContent="Kullanıcı adı ve şifre girin.";return}$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");load()};
$("logoutBtn").onclick=()=>{$("appView").classList.add("hidden");$("loginView").classList.remove("hidden");$("password").value=""};
function load(){ $("statGroups").textContent=demo.groups.length; $("statPersonnel").textContent=0; $("statPending").textContent=0; $("statChanges").textContent=0; renderGroups(); populateGroups(); }
function showPage(page){document.querySelectorAll(".page").forEach(p=>p.classList.add("hidden"));$(page).classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===page));$("pageTitle").textContent={dashboard:"Dashboard",groups:"Personel Grupları",forms:"Form Tasarımı",links:"Başvuru Linkleri",personnel:"Personeller",logs:"İşlem Logları",settings:"Ayarlar"}[page];if(page==="groups")renderGroups();if(page==="forms")renderBuilder();if(page==="links")renderLinks();if(page==="personnel")$("personnelTable").innerHTML='<div class="empty">Backend bağlantısından sonra gerçek personel kayıtları burada gösterilecek.</div>';if(page==="logs")$("logsTable").innerHTML='<div class="empty">Backend bağlantısından sonra gerçek DOCUMENT_LOG kayıtları burada gösterilecek.</div>'}
function renderGroups(){$("groupsTable").innerHTML='<table class="table"><thead><tr><th>Grup</th><th>Açıklama</th><th>Personel</th><th>Belge</th><th>Durum</th></tr></thead><tbody>'+demo.groups.map(g=>`<tr><td><strong>${esc(g.name)}</strong></td><td>${esc(g.description)}</td><td>${g.people}</td><td>${g.docs}</td><td><span class="pill ok">Aktif</span></td></tr>`).join("")+'</tbody></table>'}
$("newGroupBtn").onclick=()=>{const n=prompt("Grup adı:");if(!n)return;demo.groups.push({id:"GRP-"+Date.now(),name:n.toUpperCase(),description:"Yeni personel grubu",people:0,docs:0});load();showPage("groups")};
function populateGroups(){$("formGroup").innerHTML=demo.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join("")}
document.querySelectorAll(".palette button").forEach(b=>b.onclick=()=>{const f={id:"FLD-"+Date.now()+Math.random(),type:b.dataset.type,label:typeNames[b.dataset.type],required:false,code:["document","photo"].includes(b.dataset.type)?b.dataset.type.toUpperCase():""};demo.fields.push(f);selectedField=f.id;renderBuilder()});
function renderBuilder(){populateGroups();$("canvasTitle").textContent=$("formName").value||"Personel Başvuru Formu";$("emptyFields").classList.toggle("hidden",demo.fields.length>0);$("fieldList").innerHTML=demo.fields.map(f=>`<div class="field-row ${selectedField===f.id?"selected":""}" data-id="${f.id}"><span>☰</span><div class="field-main"><strong>${esc(f.label)}</strong><small>${typeNames[f.type]} ${f.required?"• Zorunlu":""}</small></div><button class="remove" data-remove="${f.id}">Sil</button></div>`).join("");document.querySelectorAll(".field-row").forEach(r=>r.onclick=e=>{if(e.target.dataset.remove)return;selectedField=r.dataset.id;renderBuilder()});document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=e=>{e.stopPropagation();demo.fields=demo.fields.filter(f=>f.id!==b.dataset.remove);selectedField=null;renderBuilder()});renderProperties()}
function renderProperties(){const f=demo.fields.find(x=>x.id===selectedField);if(!f){$("propertiesBody").innerHTML='<div class="empty">Düzenlemek için bir alan seçin.</div>';return}$("propertiesBody").innerHTML=`<div class="property"><label>Etiket</label><input id="propLabel" value="${esc(f.label)}"></div>${["document","photo"].includes(f.type)?`<div class="property"><label>Belge Kodu</label><input id="propCode" value="${esc(f.code||"")}"></div>`:""}<div class="property check"><input id="propReq" type="checkbox" ${f.required?"checked":""}> <label for="propReq">Zorunlu alan</label></div>${["document","photo"].includes(f.type)?`<div class="property check"><input id="propReplace" type="checkbox" ${f.replaceAllowed!==false?"checked":""}> <label for="propReplace">Sonradan değiştirilebilir</label></div><div class="property check"><input id="propApproval" type="checkbox" ${f.hrApproval?"checked":""}> <label for="propApproval">HR onayı gerekli</label></div>`:""}`;$("propLabel").oninput=e=>{f.label=e.target.value;renderBuilder()};$("propReq").onchange=e=>{f.required=e.target.checked;renderBuilder()};if($("propCode"))$("propCode").oninput=e=>f.code=e.target.value;if($("propReplace"))$("propReplace").onchange=e=>f.replaceAllowed=e.target.checked;if($("propApproval"))$("propApproval").onchange=e=>f.hrApproval=e.target.checked}
$("saveFormBtn").onclick=()=>alert("Form tasarımının arayüzü hazır. Bir sonraki aşamada Kaydet işlemini Google Sheets + Apps Script'e bağlayacağız.");
$("previewBtn").onclick=()=>alert("Önizleme motoru sonraki aşamada personel formuyla aynı alan tanımlarını kullanacak.");
$("newLinkBtn").onclick=()=>{const g=demo.groups[0],token=Math.random().toString(36).slice(2,10).toUpperCase();demo.links.push({group:g.name,token,date:new Date().toLocaleString("tr-TR")});renderLinks()};
function renderLinks(){if(!demo.links.length){$("linksTable").innerHTML='<div class="empty">Henüz başvuru linki oluşturulmadı.</div>';return}$("linksTable").innerHTML='<table class="table"><thead><tr><th>Grup</th><th>Token</th><th>Oluşturulma</th><th>Durum</th></tr></thead><tbody>'+demo.links.map(x=>`<tr><td>${esc(x.group)}</td><td><code>${esc(x.token)}</code></td><td>${esc(x.date)}</td><td><span class="pill ok">Aktif</span></td></tr>`).join("")+'</tbody></table>'}
